#include "runtime/TypedArrayType.cpp"
#include "runtime/TypeofType.cpp"
#include "runtime/VM.cpp"
#include "runtime/VMEntryScope.cpp"
#include "runtime/VMTraps.cpp"
#include "runtime/VarOffset.cpp"
#include "runtime/Watchdog.cpp"
#include "runtime/WeakMapConstructor.cpp"
