#include "JSWebGLRenderbuffer.cpp"
#include "JSWebGLRenderingContext.cpp"
#include "JSWebGLRenderingContextBase.cpp"
#include "JSWebGLSampler.cpp"
#include "JSWebGLShader.cpp"
#include "JSWebGLShaderPrecisionFormat.cpp"
#include "JSWebGLSync.cpp"
#include "JSWebGLTexture.cpp"
