#include "Modules/indexeddb/shared/IDBRequestData.cpp"
#include "Modules/indexeddb/shared/IDBResourceIdentifier.cpp"
#include "Modules/indexeddb/shared/IDBResultData.cpp"
#include "Modules/indexeddb/shared/IDBTransactionInfo.cpp"
#include "Modules/indexeddb/shared/IndexKey.cpp"
#include "Modules/mediacapabilities/MediaCapabilities.cpp"
#include "Modules/mediacapabilities/NavigatorMediaCapabilities.cpp"
#include "Modules/mediacontrols/MediaControlsHost.cpp"
