#include "inspector/agents/worker/WorkerAuditAgent.cpp"
#include "inspector/agents/worker/WorkerConsoleAgent.cpp"
#include "inspector/agents/worker/WorkerDOMDebuggerAgent.cpp"
#include "inspector/agents/worker/WorkerDebuggerAgent.cpp"
#include "inspector/agents/worker/WorkerNetworkAgent.cpp"
#include "inspector/agents/worker/WorkerRuntimeAgent.cpp"
