#include "xml/DOMParser.cpp"
#include "xml/NativeXPathNSResolver.cpp"
#include "xml/XMLErrors.cpp"
#include "xml/XMLHttpRequest.cpp"
#include "xml/XMLHttpRequestProgressEvent.cpp"
#include "xml/XMLHttpRequestProgressEventThrottle.cpp"
#include "xml/XMLHttpRequestUpload.cpp"
#include "xml/XMLSerializer.cpp"
