#include "platform/graphics/filters/FEDropShadow.cpp"
#include "platform/graphics/filters/FEFlood.cpp"
#include "platform/graphics/filters/FEGaussianBlur.cpp"
#include "platform/graphics/filters/FELighting.cpp"
#include "platform/graphics/filters/FEMerge.cpp"
#include "platform/graphics/filters/FEMorphology.cpp"
#include "platform/graphics/filters/FEOffset.cpp"
#include "platform/graphics/filters/FESpecularLighting.cpp"
