#include "rendering/svg/RenderSVGForeignObject.cpp"
#include "rendering/svg/RenderSVGGradientStop.cpp"
#include "rendering/svg/RenderSVGHiddenContainer.cpp"
#include "rendering/svg/RenderSVGImage.cpp"
#include "rendering/svg/RenderSVGInline.cpp"
#include "rendering/svg/RenderSVGInlineText.cpp"
#include "rendering/svg/RenderSVGModelObject.cpp"
#include "rendering/svg/RenderSVGPath.cpp"
