#include "JSWorkerType.cpp"
#include "JSWorklet.cpp"
#include "JSWorkletGlobalScope.cpp"
#include "JSWritableStream.cpp"
#include "JSXMLDocument.cpp"
#include "JSXMLHttpRequest.cpp"
#include "JSXMLHttpRequestEventTarget.cpp"
#include "JSXMLHttpRequestProgressEvent.cpp"
