#include "JSGPUTextureDescriptor.cpp"
#include "JSGPUTextureFormat.cpp"
#include "JSGPUTextureUsage.cpp"
#include "JSGPUUncapturedErrorEvent.cpp"
#include "JSGPUValidationError.cpp"
#include "JSGPUVertexAttributeDescriptor.cpp"
#include "JSGPUVertexBufferDescriptor.cpp"
#include "JSGPUVertexInputDescriptor.cpp"
