#include "animation/AnimationEffect.cpp"
#include "animation/AnimationEventBase.cpp"
#include "animation/AnimationPlaybackEvent.cpp"
#include "animation/AnimationTimeline.cpp"
#include "animation/CSSAnimation.cpp"
#include "animation/CSSTransition.cpp"
#include "animation/DeclarativeAnimation.cpp"
#include "animation/DocumentTimeline.cpp"
