#include "JSHTMLInputElement.cpp"
#include "JSHTMLInputElementEntriesAPI.cpp"
#include "JSHTMLKeygenElement.cpp"
#include "JSHTMLLIElement.cpp"
#include "JSHTMLLabelElement.cpp"
#include "JSHTMLLegendElement.cpp"
#include "JSHTMLLinkElement.cpp"
#include "JSHTMLMapElement.cpp"
