#include "JSFetchRequestCredentials.cpp"
#include "JSFetchRequestInit.cpp"
#include "JSFetchRequestMode.cpp"
#include "JSFetchRequestRedirect.cpp"
#include "JSFetchResponse.cpp"
#include "JSFile.cpp"
#include "JSFileCallback.cpp"
#include "JSFileError.cpp"
