#include "svg/SVGFEFuncBElement.cpp"
#include "svg/SVGFEFuncGElement.cpp"
#include "svg/SVGFEFuncRElement.cpp"
#include "svg/SVGFEGaussianBlurElement.cpp"
#include "svg/SVGFEImageElement.cpp"
#include "svg/SVGFELightElement.cpp"
#include "svg/SVGFEMergeElement.cpp"
#include "svg/SVGFEMergeNodeElement.cpp"
