#include "rendering/style/StyleSurroundData.cpp"
#include "rendering/style/StyleTransformData.cpp"
#include "rendering/style/StyleVisualData.cpp"
#include "rendering/style/TextSizeAdjustment.cpp"
#include "rendering/style/WillChangeData.cpp"
#include "rendering/svg/RenderSVGBlock.cpp"
#include "rendering/svg/RenderSVGContainer.cpp"
#include "rendering/svg/RenderSVGEllipse.cpp"
