#include "rendering/svg/RenderSVGResourceMarker.cpp"
#include "rendering/svg/RenderSVGResourceMasker.cpp"
#include "rendering/svg/RenderSVGResourcePattern.cpp"
#include "rendering/svg/RenderSVGResourceRadialGradient.cpp"
#include "rendering/svg/RenderSVGResourceSolidColor.cpp"
#include "rendering/svg/RenderSVGRoot.cpp"
#include "rendering/svg/RenderSVGShape.cpp"
#include "rendering/svg/RenderSVGTSpan.cpp"
