#include "JSCacheQueryOptions.cpp"
#include "JSCanvasCaptureMediaStreamTrack.cpp"
#include "JSCanvasCompositing.cpp"
#include "JSCanvasDirection.cpp"
#include "JSCanvasDrawImage.cpp"
#include "JSCanvasDrawPath.cpp"
#include "JSCanvasFillRule.cpp"
#include "JSCanvasFillStrokeStyles.cpp"
