#include "JSPositionOptions.cpp"
#include "JSPostMessageOptions.cpp"
#include "JSProcessingInstruction.cpp"
#include "JSProgressEvent.cpp"
#include "JSPromiseRejectionEvent.cpp"
#include "JSPublicKeyCredential.cpp"
#include "JSPublicKeyCredentialCreationOptions.cpp"
#include "JSPublicKeyCredentialDescriptor.cpp"
