#include "dom/DOMRectReadOnly.cpp"
#include "dom/DOMStringList.cpp"
#include "dom/DataTransfer.cpp"
#include "dom/DataTransferItem.cpp"
#include "dom/DataTransferItemList.cpp"
#include "dom/DatasetDOMStringMap.cpp"
#include "dom/DecodedDataDocumentParser.cpp"
#include "dom/DeviceMotionController.cpp"
