#include "JSPerformanceMark.cpp"
#include "JSPerformanceMeasure.cpp"
#include "JSPerformanceNavigation.cpp"
#include "JSPerformanceObserver.cpp"
#include "JSPerformanceObserverCallback.cpp"
#include "JSPerformanceObserverEntryList.cpp"
#include "JSPerformancePaintTiming.cpp"
#include "JSPerformanceResourceTiming.cpp"
