#include "JSMerchantValidationEvent.cpp"
#include "JSMessageChannel.cpp"
#include "JSMessageEvent.cpp"
#include "JSMessagePort.cpp"
#include "JSMouseEvent.cpp"
#include "JSMouseEventInit.cpp"
#include "JSMutationCallback.cpp"
#include "JSMutationEvent.cpp"
