#include "JSMutationObserver.cpp"
#include "JSMutationRecord.cpp"
#include "JSNamedNodeMap.cpp"
#include "JSNavigator.cpp"
#include "JSNavigatorBeacon.cpp"
#include "JSNavigatorClipboard.cpp"
#include "JSNavigatorCredentials.cpp"
#include "JSNavigatorGPU.cpp"
