/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"

#if ENABLE(APPLE_PAY_SESSION_V3)

#include "JSApplePayShippingMethodUpdate.h"

#include "JSApplePayLineItem.h"
#include "JSDOMConvertSequences.h"
#include <JavaScriptCore/JSArray.h>
#include <JavaScriptCore/JSCInlines.h>


namespace WebCore {
using namespace JSC;

#if ENABLE(APPLE_PAY_SESSION_V3)

template<> ApplePayShippingMethodUpdate convertDictionary<ApplePayShippingMethodUpdate>(JSGlobalObject& lexicalGlobalObject, JSValue value)
{
    VM& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    bool isNullOrUndefined = value.isUndefinedOrNull();
    auto* object = isNullOrUndefined ? nullptr : value.getObject();
    if (UNLIKELY(!isNullOrUndefined && !object)) {
        throwTypeError(&lexicalGlobalObject, throwScope);
        return { };
    }
    ApplePayShippingMethodUpdate result;
    JSValue newLineItemsValue;
    if (isNullOrUndefined)
        newLineItemsValue = jsUndefined();
    else {
        newLineItemsValue = object->get(&lexicalGlobalObject, Identifier::fromString(vm, "newLineItems"));
        RETURN_IF_EXCEPTION(throwScope, { });
    }
    if (!newLineItemsValue.isUndefined()) {
        result.newLineItems = convert<IDLSequence<IDLDictionary<ApplePayLineItem>>>(lexicalGlobalObject, newLineItemsValue);
        RETURN_IF_EXCEPTION(throwScope, { });
    }
    JSValue newTotalValue;
    if (isNullOrUndefined)
        newTotalValue = jsUndefined();
    else {
        newTotalValue = object->get(&lexicalGlobalObject, Identifier::fromString(vm, "newTotal"));
        RETURN_IF_EXCEPTION(throwScope, { });
    }
    if (!newTotalValue.isUndefined()) {
        result.newTotal = convert<IDLDictionary<ApplePayLineItem>>(lexicalGlobalObject, newTotalValue);
        RETURN_IF_EXCEPTION(throwScope, { });
    } else {
        throwRequiredMemberTypeError(lexicalGlobalObject, throwScope, "newTotal", "ApplePayShippingMethodUpdate", "ApplePayLineItem");
        return { };
    }
    return result;
}

#endif

} // namespace WebCore

#endif // ENABLE(APPLE_PAY_SESSION_V3)
