partial interface WorkerGlobalScope {
    [EnabledAtRuntime=CacheAPI, SecureContext] attribute DOMCacheConstructor Cache;
    [EnabledAtRuntime=CacheAPI, SecureContext] attribute DOMCacheStorageConstructor CacheStorage;
    [EnabledAtRuntime=FetchAPI] attribute FetchHeadersConstructor Headers;
    [EnabledAtRuntime=FetchAPI] attribute FetchRequestConstructor Request;
    [EnabledAtRuntime=FetchAPI] attribute FetchResponseConstructor Response;
    [Conditional=STREAMS_API] attribute ByteLengthQueuingStrategyConstructor ByteLengthQueuingStrategy;
    [Conditional=STREAMS_API] attribute CountQueuingStrategyConstructor CountQueuingStrategy;
    [Conditional=STREAMS_API, PrivateIdentifier] attribute ReadableByteStreamControllerConstructor ReadableByteStreamController;
    [Conditional=STREAMS_API, PrivateIdentifier, PublicIdentifier] attribute ReadableStreamConstructor ReadableStream;
    [Conditional=STREAMS_API, PrivateIdentifier] attribute ReadableStreamBYOBReaderConstructor ReadableStreamBYOBReader;
    [Conditional=STREAMS_API, PrivateIdentifier] attribute ReadableStreamBYOBRequestConstructor ReadableStreamBYOBRequest;
    [Conditional=STREAMS_API, PrivateIdentifier] attribute ReadableStreamDefaultControllerConstructor ReadableStreamDefaultController;
    [Conditional=STREAMS_API, PrivateIdentifier] attribute ReadableStreamDefaultReaderConstructor ReadableStreamDefaultReader;
    attribute CloseEventConstructor CloseEvent;
    [EnabledAtRuntime=WebSocket] attribute WebSocketConstructor WebSocket;
    [Conditional=WEB_CRYPTO] attribute CryptoKeyConstructor CryptoKey;
    [Conditional=WEB_CRYPTO] attribute SubtleCryptoConstructor SubtleCrypto;
    attribute DOMMatrixConstructor DOMMatrix;
    attribute DOMMatrixReadOnlyConstructor DOMMatrixReadOnly;
    [Conditional=CSS_TYPED_OM, EnabledAtRuntime=CSSTypedOM] attribute StylePropertyMapReadOnlyConstructor StylePropertyMapReadOnly;
    [Conditional=CSS_TYPED_OM, EnabledAtRuntime=CSSTypedOM] attribute TypedOMCSSImageValueConstructor CSSImageValue;
    [Conditional=CSS_TYPED_OM, EnabledAtRuntime=CSSTypedOM] attribute TypedOMCSSNumericValueConstructor CSSNumericValue;
    [Conditional=CSS_TYPED_OM, EnabledAtRuntime=CSSTypedOM] attribute TypedOMCSSStyleValueConstructor CSSStyleValue;
    [Conditional=CSS_TYPED_OM, EnabledAtRuntime=CSSTypedOM] attribute TypedOMCSSUnitValueConstructor CSSUnitValue;
    [Conditional=CSS_TYPED_OM, EnabledAtRuntime=CSSTypedOM] attribute TypedOMCSSUnparsedValueConstructor CSSUnparsedValue;
    attribute AbortControllerConstructor AbortController;
    attribute AbortSignalConstructor AbortSignal;
    attribute CustomEventConstructor CustomEvent;
    attribute DOMExceptionConstructor DOMException;
    attribute DOMPointConstructor DOMPoint;
    attribute DOMPointReadOnlyConstructor DOMPointReadOnly;
    attribute DOMQuadConstructor DOMQuad;
    attribute DOMRectConstructor DOMRect;
    attribute DOMRectReadOnlyConstructor DOMRectReadOnly;
    attribute ErrorEventConstructor ErrorEvent;
    attribute EventConstructor Event;
    attribute EventTargetConstructor EventTarget;
    [Conditional=CHANNEL_MESSAGING] attribute MessageChannelConstructor MessageChannel;
    attribute MessageEventConstructor MessageEvent;
    attribute MessagePortConstructor MessagePort;
    attribute ProgressEventConstructor ProgressEvent;
    attribute PromiseRejectionEventConstructor PromiseRejectionEvent;
    attribute TextDecoderConstructor TextDecoder;
    attribute TextEncoderConstructor TextEncoder;
    attribute BlobConstructor Blob;
    attribute FileConstructor File;
    attribute FileListConstructor FileList;
    attribute FileReaderConstructor FileReader;
    attribute FileReaderSyncConstructor FileReaderSync;
    attribute DOMFormDataConstructor FormData;
    attribute DOMURLConstructor URL;
    [EnabledAtRuntime=ImageBitmap] attribute ImageBitmapConstructor ImageBitmap;
    attribute ImageDataConstructor ImageData;
    [Conditional=OFFSCREEN_CANVAS, EnabledAtRuntime=OffscreenCanvas] attribute OffscreenCanvasConstructor OffscreenCanvas;
    attribute URLSearchParamsConstructor URLSearchParams;
    attribute CanvasGradientConstructor CanvasGradient;
    attribute CanvasPatternConstructor CanvasPattern;
    attribute Path2DConstructor Path2D;
    attribute CryptoConstructor Crypto;
    attribute EventSourceConstructor EventSource;
    attribute PerformanceConstructor Performance;
    [EnabledAtRuntime=PerformanceTimeline] attribute PerformanceEntryConstructor PerformanceEntry;
    [EnabledAtRuntime=UserTiming] attribute PerformanceMarkConstructor PerformanceMark;
    [EnabledAtRuntime=UserTiming] attribute PerformanceMeasureConstructor PerformanceMeasure;
    [EnabledAtRuntime=PerformanceTimeline] attribute PerformanceObserverConstructor PerformanceObserver;
    [EnabledAtRuntime=PerformanceTimeline] attribute PerformanceObserverEntryListConstructor PerformanceObserverEntryList;
    [EnabledAtRuntime=ResourceTiming] attribute PerformanceResourceTimingConstructor PerformanceResourceTiming;
    [EnabledAtRuntime=ServerTiming] attribute PerformanceServerTimingConstructor PerformanceServerTiming;
    attribute WorkerNavigatorConstructor WorkerNavigator;
    attribute WorkerGlobalScopeConstructor WorkerGlobalScope;
    attribute WorkerLocationConstructor WorkerLocation;
    attribute XMLHttpRequestEventTargetConstructor XMLHttpRequestEventTarget;
    attribute XMLHttpRequestUploadConstructor XMLHttpRequestUpload;
};
